//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int Patient_id { get; set; }
        public Nullable<int> Patient_number { get; set; }
        public string MedicalAid_number { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Emailaddress { get; set; }
        public string Telephonenumber { get; set; }
        public string Address { get; set; }
    }
}
