//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomAcessControl
    {
        public int RoomAcessControl_id { get; set; }
        public string Room_number { get; set; }
        public string DateTime { get; set; }
        public string Permission_status { get; set; }
        public string Rfid_key { get; set; }
        public string Room_name { get; set; }
        public string Room_status { get; set; }
    }
}
